-- Create the 'contracts' table to store insurance contract data
CREATE TABLE public.contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    start_date date,
    end_date date,
    object_type text,
    address text,
    insurance_amount numeric,
    lat double precision,
    lng double precision,
    is_active boolean,
    region_id text
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.contracts IS 'Stores insurance contract data uploaded from Excel files.';
COMMENT ON COLUMN public.contracts.id IS 'Unique identifier for each contract record.';
COMMENT ON COLUMN public.contracts.created_at IS 'Timestamp of when the record was created.';
COMMENT ON COLUMN public.contracts.start_date IS 'The start date of the insurance contract.';
COMMENT ON COLUMN public.contracts.end_date IS 'The end date of the insurance contract.';
COMMENT ON COLUMN public.contracts.object_type IS 'The type of object being insured (e.g., "Квартира", "Дом").';
COMMENT ON COLUMN public.contracts.address IS 'The address of the insured object.';
COMMENT ON COLUMN public.contracts.insurance__amount IS 'The total insurance amount.';
COMMENT ON COLUMN public.contracts.lat IS 'The latitude of the address.';
COMMENT ON COLUMN public.contracts.lng IS 'The longitude of the address.';
COMMENT ON COLUMN public.contracts.is_active IS 'Indicates if the contract is currently active.';
COMMENT ON COLUMN public.contracts.region_id IS 'The ID of the administrative region the contract belongs to.';

-- Enable Row Level Security (RLS) for the 'contracts' table
-- This is a critical security measure to ensure data is accessed according to your policies.
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to view all contracts.
-- This is suitable for public data. If data should be user-specific,
-- you would change `USING (true)` to `USING (auth.uid() = user_id)`.
CREATE POLICY "Allow public read access"
ON public.contracts
FOR SELECT
USING (true);

-- Create a policy that allows any authenticated user to insert new contracts.
-- If you want to restrict this to specific users, you would modify the `CHECK` condition.
-- Using `(true)` for now to allow any client with the anon key to insert.
CREATE POLICY "Allow public insert access"
ON public.contracts
FOR INSERT
WITH CHECK (true);

-- Create a policy that allows any authenticated user to update contracts.
-- This is consistent with the current security model. For a more secure setup,
-- this would be restricted to specific roles, e.g., USING (auth.role() = 'admin').
CREATE POLICY "Allow public update access"
ON public.contracts
FOR UPDATE
USING (true)
WITH CHECK (true);

-- Create the 'users' table to store user data for authentication and role-based access control
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    role text NOT NULL CHECK (role IN ('admin', 'rating_agency', 'risk_manager')),
    full_name text,
    is_active boolean DEFAULT true
);

-- Add comments to the users table and its columns for better understanding
COMMENT ON TABLE public.users IS 'Хранит данные пользователей системы';
COMMENT ON COLUMN public.users.username IS 'Уникальное имя пользователя для входа';
COMMENT ON COLUMN public.users.password_hash IS 'Хешированный пароль';
COMMENT ON COLUMN public.users.role IS 'Роль пользователя: admin, rating_agency, risk_manager';
COMMENT ON COLUMN public.users.full_name IS 'Полное имя пользователя';
COMMENT ON COLUMN public.users.is_active IS 'Активен ли аккаунт пользователя';

-- Enable Row Level Security (RLS) for the 'users' table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows users to view their own data
CREATE POLICY "Users can view own data"
ON public.users
FOR SELECT
USING (auth.uid()::text = id::text);
